# Generated by Django 4.0.5 on 2022-07-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_about_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='uknown', max_length=200),
        ),
    ]
